name: Run Trivia Promo

on:
  schedule:
    - cron: '0 0 * * *'  # 8 PM EST = 0:00 UTC (during DST)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot37
        run: python bots/bot37/bot.py
